create table if not exists public.whiskey_contest (
  id bigint generated by default as identity primary key,
  name text not null unique,
  count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table public.whiskey_contest enable row level security;

-- Policies
create policy "Enable read access for all users" on public.whiskey_contest for select using (true);
create policy "Enable insert for all users" on public.whiskey_contest for insert with check (true);
create policy "Enable update for all users" on public.whiskey_contest for update using (true);

-- Realtime
alter publication supabase_realtime add table whiskey_contest;
