import pg from 'pg';

const client = new pg.Client({
  connectionString: 'postgresql://postgres:Wjdtn4605!@db.oiyzxdrssxobsqjtlyjf.supabase.co:5432/postgres'
});

async function run() {
  try {
    await client.connect();
    console.log('Connected to DB');

    const query = `
      create table if not exists public.stock_counts (
        id bigint generated by default as identity primary key,
        name text not null unique,
        count integer default 0,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );
      
      -- Enable RLS
      alter table public.stock_counts enable row level security;

      -- Policies (Use DO block to avoid error if policy exists)
      do $$
      begin
        if not exists (select 1 from pg_policies where tablename = 'stock_counts' and policyname = 'Enable read access for all users') then
          create policy "Enable read access for all users" on public.stock_counts for select using (true);
        end if;
        if not exists (select 1 from pg_policies where tablename = 'stock_counts' and policyname = 'Enable insert for all users') then
          create policy "Enable insert for all users" on public.stock_counts for insert with check (true);
        end if;
        if not exists (select 1 from pg_policies where tablename = 'stock_counts' and policyname = 'Enable update for all users') then
          create policy "Enable update for all users" on public.stock_counts for update using (true);
        end if;
      end
      $$;

      -- Realtime
      alter publication supabase_realtime add table stock_counts;
    `;
    
    await client.query(query);
    console.log('Table created successfully!');
  } catch (err) {
    console.error('Error:', err);
  } finally {
    await client.end();
  }
}

run();
